name: Build and Deploy 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CONTAINER_REGISTRY_URL: ${{ vars.CONTAINER_REGISTRY_URL}}
      CONTAINER_REGISTRY_REPOSITORY_NAME: ${{ vars.CONTAINER_REGISTRY_REPOSITORY_NAME }}
    outputs:
      image-version: ${{ steps.set-variables.outputs.IMAGE_VERSION }}
    steps:
      
      - name: ECHO VARIABLES
        run: |
          echo "IMAGE_VERSION = $IMAGE_VERSION"
          echo "CONTAINER_REGISTRY_URL = $CONTAINER_REGISTRY_URL" 
          echo "CONTAINER_REGISTRY_REPOSITORY_NAME = $CONTAINER_REGISTRY_REPOSITORY_NAME"  

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to ACR
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CONTAINER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Get the current date
        id: date
        run: echo "tag=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
        
      - name: Build & Push UdpProxy.Server
        uses: docker/build-push-action@v2
        with:
          context: ./UdpProxy.Server
          file: ./UdpProxy.Server/Dockerfile
          push: true
          tags: ${{ env.CONTAINER_REGISTRY_URL }}/${{ env.CONTAINER_REGISTRY_REPOSITORY_NAME }}:${{ steps.date.outputs.tag }}

      - name: Set image name for other jobs
        id: set-variables
        run: |
          echo "IMAGE_VERSION=${{ steps.date.outputs.tag }}" >> $GITHUB_OUTPUT
